version: '2'

services:
  postgresql:
    image: registry.drycc.cc/drycc-addons/postgresql:14
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/drycc/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

volumes:
  postgresql_data:
    driver: local
