version: '2'

services:
  postgresql:
    image: docker.io/drycc-addons/postgresql:14.2
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/drycc/postgresql'
    environment:
      - 'DRYCC_DEBUG=true'
      - 'ALLOW_EMPTY_PASSWORD=yes'

volumes:
  postgresql_data:
    driver: local
